name: Build and Run with CMake

on:
  push:
    branches:
      - main 

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install CMake
      run: sudo apt-get -y install cmake = 3.28
      
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Run program
      run: ./build/TESTS